- name: install db
  tags: db
  apt:
    name: mariadb-server 
    state: latest
- name: copy file 
  tags: apache
  copy:
     src: default_site.html
     dest: /var/www/index.html
     owner: root
     group: root
     mode: 0644
- name: changing email for alla file
  tags: apache
  lineinfile:
        path: /home/lubana11/alla
        regexp: '^email'
        line: email LUBANA6@gmail.ask
  notify: restart_apache
